const M=L.map('map').setView([-9.8,-48.5],7),T={sat:L.tileLayer('https://mt{s}.google.com/vt/lyrs=y&x={x}&y={y}&z={z}',{subdomains:['0','1','2','3'],maxZoom:21}),rua:L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19})};T.sat.addTo(M);let base='sat';
const G={t1:L.layerGroup().addTo(M),t2:L.layerGroup().addTo(M),t3:L.layerGroup().addTo(M),ch:L.layerGroup().addTo(M),tr:L.layerGroup().addTo(M),alvo:L.layerGroup().addTo(M),fim:L.layerGroup().addTo(M),sel:L.layerGroup().addTo(M),pts:L.layerGroup().addTo(M)},ON={t1:1,t2:1,t3:1,ch:1,tr:1,alvo:1,fim:1},ST={T1:['#FFD600',2.7,.95,'t1'],T2:['#00E5FF',1.9,.9,'t2'],T3:['#AB47BC',1.6,.9,'t3']};
let IX={},NA=[],D={},B={},AM={},active='',circ='',ini=null,fim=null,picked=[];
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),dig=x=>String(x??'').replace(/\D/g,''),u8=x=>{let d=dig(x);return d.length>8?d.slice(-8):d},same=(a,b)=>{a=dig(a);b=dig(b);return!!a&&!!b&&(a===b||(a.length>=8&&b.length>=8&&a.slice(-8)===b.slice(-8)))},dst=(a,b)=>{let p=Math.PI/180,x=(b[0]-a[0])*111320*Math.cos((a[1]+b[1])*p/2),y=(b[1]-a[1])*110540;return Math.hypot(x,y)},len=a=>a.slice(1).reduce((s,p,i)=>s+dst(a[i],p),0),csv=x=>'"'+String(x??'').replace(/"/g,'""')+'"';
function toast(x){let t=$('toast');if(!t){t=document.createElement('div');t.id='toast';t.style.cssText='position:fixed;bottom:28px;left:50%;transform:translateX(-50%);background:#252525;color:#fff;padding:9px 14px;border:1px solid #555;border-radius:7px;z-index:9999;font-size:12px';document.body.append(t)}t.textContent=x;t.hidden=false;clearTimeout(t._t);t._t=setTimeout(()=>t.hidden=true,3200)}
function dl(n,s,tp){let a=document.createElement('a'),u=URL.createObjectURL(new Blob([s],{type:tp}));a.href=u;a.download=n;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),800)}
function t3(v){v=String(v??'').toUpperCase();return v==='1'||v==='T1'?'T1':v==='2'||v==='T2'?'T2':'T3'}
function segs(d){let r=[];if(Array.isArray(d.segs))d.segs.forEach((s,i)=>{let p=(s[5]||[]).map(x=>[+x[0],+x[1]]).filter(x=>isFinite(x[0])&&isFinite(x[1]));if(p.length>1)r.push({id:'S_'+i,t:t3(s[4]),p})});else[['T1',d.t1],['T2',d.t2],['T3',d.t3]].forEach(([t,a])=>(a||[]).forEach((p,i)=>{p=(p||[]).map(x=>[+x[0],+x[1]]).filter(x=>isFinite(x[0])&&isFinite(x[1]));if(p.length>1)r.push({id:t+'_'+i,t,p})}));return r}
function key(x){return Array.isArray(x)?{c:x[0],x:+x[1],y:+x[2]}:{c:x?.nome??x?.codigo??x?.id??'',x:+(x?.lon??x?.longitude),y:+(x?.lat??x?.latitude)}}
function graph(d){if(d.g)return d.g;let e=segs(d).map(x=>({...x,l:len(x.p)})),n=[],m=new Map(),a=[],q=.00018,s=p=>{let x=p[0],y=p[1],gx=Math.floor(x/q),gy=Math.floor(y/q),z=-1,b=1e9;for(let i=-1;i<2;i++)for(let j=-1;j<2;j++)for(let k of(m.get(gx+i+'|'+(gy+j))||[])){let v=dst(p,[n[k].x,n[k].y]);if(v<b)b=v,z=k}if(z>=0&&b<20)return z;z=n.length;n.push({x,y});let h=gx+'|'+gy;m.set(h,[...(m.get(h)||[]),z]);return z};e.forEach((z,i)=>{z.a=s(z.p[0]);z.b=s(z.p.at(-1));(a[z.a]??=[]).push(i);(a[z.b]??=[]).push(i)});return d.g={e,n,a}}
function near(d,x,y){let g=graph(d),z=-1,b=1e9;g.n.forEach((n,i)=>{let v=dst([x,y],[n.x,n.y]);if(v<b)b=v,z=i});return b<=100?z:-1}
function cuts(d){let g=graph(d);return g.n.map((n,i)=>[n,i]).filter(([,i])=>(g.a[i]||[]).length===1)}
function style(t){return ST[t]||ST.T3}
function tog(k){ON[k]=!ON[k];$('btn-'+k).classList.toggle('on',!!ON[k]);ON[k]?M.addLayer(G[k]):M.removeLayer(G[k])}
function baseMap(){M.removeLayer(T[base]);base=base==='sat'?'rua':'sat';T[base].addTo(M);$('btn-base').textContent=base==='sat'?'Mapa':'Satélite'}
function list(f=''){f=String(f).toLowerCase();let fd=dig(f),A=Object.entries(IX).filter(([c,v])=>!f||c.toLowerCase().includes(f)||String(v.se||'').toLowerCase().includes(f)||String(v.circ||'').toLowerCase().includes(f)||(fd&&u8(c).includes(fd))).sort(),L=$('lista');$('st').textContent=A.length+' ativos';L.innerHTML='<b>ATIVOS ENCONTRADOS</b>';A.forEach(([c,v])=>{let x=document.createElement('div');x.className='it';x.innerHTML='<i class="'+(D[v.circ]?'blue':'ok')+'"></i><span><strong>'+esc(c)+'</strong><small>'+esc(v.se||'')+' · '+esc(v.circ||'')+'</small></span>';x.onclick=()=>open(c);L.append(x)});if(NA.length){let h=document.createElement('b');h.textContent='SEM VÍNCULO';L.append(h);NA.filter(c=>!f||String(c).toLowerCase().includes(f)||(fd&&u8(c).includes(fd))).forEach(c=>{let x=document.createElement('div');x.className='it dim';x.innerHTML='<i></i><span><strong>'+esc(c)+'</strong><small>Buscar pelos últimos 8 dígitos</small></span>';x.onclick=()=>{let z=Object.keys(IX).find(k=>same(k,c));z?open(z):toast('Não localizado no índice atual.')};L.append(x)})}}
async function open(c){let v=IX[c];if(!v)return;active=c;try{let d=await load(v.circ);circ=v.circ;M.setView([+v.lat,+v.lon],15);setTimeout(()=>AM[c]?.openPopup(),150);bar();box()}catch(e){toast('Erro ao carregar '+v.circ)}list($('busca').value)}
async function load(c){if(D[c])return D[c];let r=await fetch('alimentadores/'+c+'.json?'+Date.now());if(!r.ok)throw 0;let d=await r.json();graph(d);D[c]=d;draw(c,d);return d}
function pnt(o){let r=document.createElement('div');r.innerHTML='<strong>'+esc(o.c)+'</strong><small>'+esc(o.k)+' · '+esc(o.circ)+'</small>';let z=document.createElement('div');z.className='pb';[['Início',()=>start(o),'a'],['Fim',()=>end(o),'f'],['Trecho inicial',()=>{start(o);setTimeout(first,0)},'x'],['Até o final',()=>{start(o);setTimeout(last,0)},'x']].forEach(([t,fn,cl])=>{let b=document.createElement('button');b.textContent=t;b.className=cl;b.onclick=fn;z.append(b)});r.append(z);return r}
function draw(c,d){let g=graph(d),P=[];g.e.forEach((e,i)=>{let s=style(e.t),l=L.polyline(e.p.map(x=>[x[1],x[0]]),{color:s[0],weight:s[1],opacity:s[2]}).addTo(G[s[3]]);l.on('click',()=>one(c,i));P.push(...e.p.map(x=>[x[1],x[0]]))});(d.chaves||[]).map(key).filter(o=>isFinite(o.x)&&isFinite(o.y)).forEach(o=>{let z=Object.entries(IX).find(([k,v])=>v.circ===c&&same(k,o.c)),q={circ:c,k:z?'Ativo':'Chave',c:z?z[0]:o.c,x:o.x,y:o.y},m=L.circleMarker([q.y,q.x],{radius:z?8:4.5,fillColor:z?'#ff1744':'#7e57c2',color:'#fff',weight:1.5,fillOpacity:1}).bindPopup(pnt(q)).addTo(z?G.alvo:G.ch);if(z)AM[z[0]]=m;P.push([q.y,q.x])});(d.trafos||[]).map(key).filter(o=>isFinite(o.x)&&isFinite(o.y)).forEach(o=>{let q={circ:c,k:'Transformador',c:o.c,x:o.x,y:o.y};L.circleMarker([q.y,q.x],{radius:3.6,fillColor:'#1e88e5',color:'#fff',weight:1.2,fillOpacity:1}).bindPopup(pnt(q)).addTo(G.tr);P.push([q.y,q.x])});Object.entries(IX).filter(([,v])=>v.circ===c).forEach(([k,v])=>{if(AM[k])return;let q={circ:c,k:'Ativo',c:k,x:+v.lon,y:+v.lat};if(!isFinite(q.x)||!isFinite(q.y))return;AM[k]=L.circleMarker([q.y,q.x],{radius:8,fillColor:'#ff1744',color:'#fff',weight:2}).bindPopup(pnt(q)).addTo(G.alvo);P.push([q.y,q.x])});cuts(d).forEach(([n,i])=>{let q={circ:c,k:'Final de rede',c:'Final '+(i+1),x:n.x,y:n.y};L.circleMarker([q.y,q.x],{radius:4,fillColor:'#ce93d8',color:'#fff',weight:1}).bindPopup(pnt(q)).addTo(G.fim)});if(P.length)B[c]=L.latLngBounds(P)}
function start(o){let d=D[o.circ],n=near(d,o.x,o.y);if(n<0)return toast('Ponto não associado à rede.');ini={...o,n};if(fim&&fim.circ!==o.circ)fim=null;circ=o.circ;marks();box();M.closePopup()}
function end(o){let d=D[o.circ],n=near(d,o.x,o.y);if(n<0)return toast('Ponto não associado à rede.');if(ini&&ini.circ!==o.circ)return toast('Início e fim devem estar no mesmo alimentador.');fim={...o,n};circ=o.circ;marks();box();M.closePopup();if(ini)between()}
function marks(){G.pts.clearLayers();if(ini)L.circleMarker([ini.y,ini.x],{radius:8,fillColor:'#66bb6a',color:'#fff',weight:2}).addTo(G.pts);if(fim)L.circleMarker([fim.y,fim.x],{radius:8,fillColor:'#ce93d8',color:'#fff',weight:2}).addTo(G.pts)}
function box(){let b=$('sel');b.hidden=!circ;$('si').textContent=ini?ini.k+' '+ini.c:'não definido';$('sf').textContent=fim?fim.k+' '+fim.c:'não definido';$('be').disabled=!(ini&&fim);$('bi').disabled=!ini;$('bf').disabled=!ini;$('bc').disabled=!picked.length;$('bk').disabled=!picked.length}
function dij(d,o){let g=graph(d),n=g.n.length,x=Array(n).fill(Infinity),pn=Array(n).fill(-1),pe=Array(n).fill(-1),h=[[0,o]];x[o]=0;while(h.length){h.sort((a,b)=>b[0]-a[0]);let [w,u]=h.pop();if(w!==x[u])continue;for(let i of(g.a[u]||[])){let e=g.e[i],v=e.a===u?e.b:e.a,z=w+e.l;if(z<x[v])x[v]=z,pn[v]=u,pe[v]=i,h.push([z,v])}}return{x,pn,pe}}
function path(d,a,b){let r=dij(d,a),z=[];if(!isFinite(r.x[b]))return null;for(let x=b;x!==a;x=r.pn[x]){let e=r.pe[x];if(e<0)return null;z.push(e)}return z.reverse()}
function pick(ids,name){let d=D[circ],g=graph(d);ids=[...new Set(ids)].sort((a,b)=>a-b);if(!ids.length)return toast('Nenhum trecho encontrado.');G.sel.clearLayers();picked=ids.map(i=>g.e[i]);picked.forEach(e=>L.polyline(e.p.map(x=>[x[1],x[0]]),{color:'#00e676',weight:4.1}).addTo(G.sel));M.fitBounds(L.latLngBounds(picked.flatMap(e=>e.p.map(x=>[x[1],x[0]]))),{padding:[35,35]});box();toast(name+': '+picked.length+' segmento(s).')}
function between(){if(!(ini&&fim&&ini.circ===fim.circ))return toast('Defina início e fim no mesmo alimentador.');let p=path(D[circ],ini.n,fim.n);p?.length?pick(p,'Entre início e fim'):toast('Não existe caminho contínuo entre os pontos.')}
function first(){if(!ini)return;pick(graph(D[circ]).a[ini.n]||[],'Trecho inicial')}
function last(){if(!ini)return;let d=D[circ],g=graph(d),r=dij(d,ini.n),z=-1,m=-1;g.n.forEach((n,i)=>{if((g.a[i]||[]).length<=1&&isFinite(r.x[i])&&r.x[i]>m)m=r.x[i],z=i});if(z<0)return toast('Final de rede não encontrado.');let n=g.n[z];fim={circ,k:'Final de rede',c:'Final mais distante',x:n.x,y:n.y,n:z};marks();pick(path(d,ini.n,z),'Do início ao final')}
function all(){if(!circ)return toast('Selecione um ativo e carregue o alimentador.');pick(graph(D[circ]).e.map((_,i)=>i),'Todos T1 + T2 + T3')}
function one(c,i){circ=c;pick([i],'Trecho individual')}
function clearSel(){picked=[];ini=fim=null;G.sel.clearLayers();G.pts.clearLayers();box()}
function outCSV(){let d=D[circ],h=['ALIMENTADOR','SE','POLO','ORDEM','TIPO_REDE','ID_SEGMENTO','COMPRIMENTO_M','INICIO','FIM','GEOMETRIA_WKT'],r=[h];picked.forEach((e,i)=>r.push([circ,d.se||'',d.polo||'',i+1,e.t,e.id,e.l.toFixed(2),ini?.c||'',fim?.c||'','LINESTRING ('+e.p.map(x=>x[0].toFixed(7)+' '+x[1].toFixed(7)).join(', ')+')']));dl('trechos_'+circ+'.csv','\uFEFF'+r.map(x=>x.map(csv).join(';')).join('\n'),'text/csv')}
function outKML(){let s='<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document>';picked.forEach((e,i)=>s+='<Placemark><name>'+e.t+' '+(i+1)+'</name><LineString><coordinates>'+e.p.map(x=>x[0]+','+x[1]+',0').join(' ')+'</coordinates></LineString></Placemark>');dl('trechos_'+circ+'.kml',s+'</Document></kml>','application/vnd.google-earth.kml+xml')}
function bar(){let a=Object.keys(D);$('bar').innerHTML=a.length?a.map(c=>'<button data-c="'+c+'">'+c+'</button>').join('')+'<button id="wipe">Limpar mapa</button>':'Nenhum alimentador carregado';document.querySelectorAll('[data-c]').forEach(x=>x.onclick=()=>{circ=x.dataset.c;M.fitBounds(B[circ]);box()});$('wipe')?.addEventListener('click',()=>{Object.values(G).forEach(x=>x.clearLayers());D={};B={};AM={};active=circ='';clearSel();bar();list($('busca').value)})}
fetch('indice.json').then(r=>r.json()).then(x=>{IX=x.chaves||{};NA=x.nao_encontradas||[];list();bar()}).catch(()=>toast('Não foi possível carregar o índice.'));